### ISSUE TITLE
maximize seems not working

### ISSUE THREAD

**Issue by directa-it** [TamkeenLMS/electron-window-manager#16]
Hi,
I'm trying use maximize function and it seems totally not working.
I tested it on mac and it produces error.
the minimize function works well.
Thanks

**Comment by johnking** [comment]
I found the same issue with Mac.

**Comment by azain** [comment]
I am not sure that this is an issue with the library, it works well on Windows. And I just use what Electron provides, which is [this method](http://electron.atom.io/docs/api/browser-window/#winmaximize). 

Try testing this feature without using EWM and see if it's an issue with Electron itself.

**Comment by a-sync** [comment]
Closing this for now, unless someone can confirm that this is an ewm issue.
