### ISSUE TITLE
asar can't find module melanke-watchjs

### ISSUE THREAD

**Issue by gitcyrabbit** [TamkeenLMS/electron-window-manager#26]
when pack source as a asar file,
run projectname.exe,
there was an error , Error, cant find module melanke-watchjs,

in electron-window-manager package.json ,
`
   "dependencies": {

    "electron-localshortcut": "^0.6.0",

    "underscore": "^1.8.3",

    "watchjs": "git+https://github.com/melanke/Watch.JS.git"
  }
`

in index.js
`const WatchJS = require('melanke-watchjs');`

npm list

it is show

+-- electron-window-manager@1.0.4
| +-- melanke-watchjs@1.3.1 extraneous (git+https://github.com/melanke/Watch.JS.git#ea157a742c819638a8ecc9fce24e7dba39379d3c)

so  maybe this cause error

my: 

Electron 1.4.13

**Comment by graywolf336** [comment]
You sadly have to add it to your own project's dependencies.

**Comment by phortx** [comment]
This seems to be fixed, but no version is released since then. When is the next release planned?
