### ISSUE TITLE
Relative Urls

### ISSUE THREAD

**Issue by DaCardinal** [TamkeenLMS/electron-window-manager#28]
For some strange reason relative urls not loading 

> <link href="/assets/css/bootstrap.min.css" rel="stylesheet">
>   <link href="/assets/css/login.css" rel="stylesheet">
>   <script src="/assets/js/jquery.js"></script>

**Comment by TamkeenLMS** [comment]
This probably isn't an issue with EWM. Open the developer tools and try to do some debugging. But you mainly need to make sure that the HTML file being viewed is beside the assets folder (in this case), or maybe lose the starting /

**Comment by DaCardinal** [comment]
I did a bit of tinkering and realized that the reason this was happening was in the loadURL. You were parsing the contents of  the html in a URI component. I have a ready solution I can push. I did a bit of testing on it and works fine now. Declared these at the top of the index.js already declared constants
const UrlPath = require('url');
const DirPath = require('path');
const Cheerio = require('cheerio');

 Here's my solution. 
 
/**
     * Load a URL into the window
     * */
    Window.prototype.loadURL = function(url, options){
        // Ready the url
        url = utils.readyURL(url || this.setup.url);

        var instance = this,
            layout = this.setup.layout !== false
                ?(this.setup.layout || windowManager.config.defaultLayout) :false;

        // If a layout is specified
        var layoutFile = layouts.get(layout);
        if(layout && !layoutFile){
            console.log('The layout "' + layout +'" wasn\'t found!');
        }

        if(layout && layoutFile && url.substring(0, 4) != 'http'){
            var layoutPath = layoutFile.replace('file://', '');
            var layoutUrl = UrlPath.format({
              pathname: DirPath.join(layoutPath),
              protocol: 'file:',
              slashes: true
            })

            // Load the the layout first
            FileSystem.readFile(layoutFile, 'utf-8', function(error, layoutCode){
                if(error){
                    console.log('Couldn\'t load the layout file: ' + layoutFile);

                    // Take the page down!
                    instance.down();

                    return false;
                }

                // Load the targeted file body
                FileSystem.readFile(url, 'utf-8', function(error, content){
                    if(error){
                        console.log('Can not find the he targeted page :' + url);

                        // Take the page down!
                        instance.down();

                        return false;
                    }

                    // Get the final body
                    content = layoutCode.replace('{{content}}', content);
                    var htmlCheerio = Cheerio.load(content);
                    var htmlBody = htmlCheerio('body');

                    // Load the final output
                    // instance.html(content, options);

                    instance.content().loadURL(layoutUrl, options);
                    instance.object.webContents.on('dom-ready', function(e){
                      e.preventDefault();
                      var test = htmlBody.html().replace(/\s{2,}/g, '').replace(/\//gi, '\\\/').replace(/"/g, '\\\'');
                      instance.object.webContents.executeJavaScript("$('body').html(\"" + test  + "\")");
                    })
                });
            });

        }else{
            // Load the passed url
            instance.content().loadURL(url, options);
        }
    };

**Comment by loicboyeldieu** [comment]
Hi DaCardinal,
I have the same problem that you, my css file in layout is not loaded.
How could I use your function?

Thnaks

**Comment by DaCardinal** [comment]
Hi @loicboyeldieu, 

So I created an option in the configs called 'assets' which took in the base url of my assets. In the html file I used handlebars such as `{{assets}}` to replace the asset base url and in the index.js file I replaced those handles bars before the html page was loaded using Cheerio. Alternatively an improvement for this library will be to use handlebars so you could replace content and the like. I put in a pull request but don't know how far with that yet ask @TamkeenLMS. Hope this helps, I could upload my source code if you need it. 

Thanks

**Comment by loicboyeldieu** [comment]
Yes it helped! I did not fixed my layout problem yet. Still inverstigating :) Thanks.

**Comment by amisra24x7** [comment]
Is there any way to by pass the layout completely? - It can be nuisance if you don't have too many common  types of windows.

**Comment by a-sync** [comment]
If you don't specify a layout, it will simply load the passed url.
Most of this got merged, so closing this.
