### ISSUE TITLE
window.html() doesn't support HTML written in utf-8

### ISSUE THREAD

**Issue by k2s** [TamkeenLMS/electron-window-manager#36]
This works: window.content().loadURL('data:text/html;charset=utf-8,' + html)

But implementation:
```
  Window.prototype.html = function(code, options){
        this.content().loadURL('data:text/html,' + code, options);
    };
```
doesn't give possibility to specify the charset.

I tried also to pass as  options `{extraHeaders: 'Content-Type: text/html; charset=utf-8\n'}` , but that also doesn't work.

As solution I would suggest to add 3th parameter charset.

**Comment by a-sync** [comment]
Since the layouts contents are also loaded using utf-8 encoding i think this should be the default setting.
```javascript
this.content().loadURL('data:text/html;charset=utf-8,' + code, options);
```

Not sure about your use case but you can also set the page's encoding explicitly the following way:
```html
<head>
<meta charset="utf-8">
</head>
```
