### ISSUE TITLE
Can not launch window from render process

### ISSUE THREAD

**Issue by Zyles** [TamkeenLMS/electron-window-manager#39]
Same problem as this: https://github.com/TamkeenLMS/electron-window-manager/issues/9

Should re-open that issue until fixed.

```
var myWindow = windowManager.createNew('myWindow', 'Stuff', false, false, false, false)
myWindow.loadURL('/login')
myWindow.open()
```

`Uncaught Error: Could not call remote function ''. Check that the function signature is correct.`

Is the documentation outdated? Because nothing I try works.

**Comment by TamkeenLMS** [comment]
Hi there

I am not sure, it's been awhile since I last updated (or used) this library, or Electron for that matter. Try to debug more and If you find a solution please make PR.

Good luck

**Comment by pascallieverse** [comment]
Hey I got the same issue,

Started a clean electron-quick-start-master on windows 10, and added the following code to to the index.html:

`    var remote = require('electron').remote;
    var windowManager = remote.require('electron-window-manager');
 
    // Create a new window
    var win2 = windowManager.createNew('win23', 'Windows #2');
    win2.loadURL('/test.html');
    win2.open();`

This gives the same error as above mentioned. (used different urls, like direct file,  http and https)

I tried to find where the index.js of the electron-window-manager crashes, this happens on line 303:
`instance.content().loadURL(url, options);`
Before this line everything runs, after that line it doesn't.

**Comment by pascallieverse** [comment]
Code works when you define the url in the createNew function:
`    var win2 = windowManager.createNew('win2', 'Windows #2', "https://github.com/TamkeenLMS/electron-window-manager/", false, {}, false);

    win2.open();`

I cant debug further because I cant find something that has to do with content().
Instance just returns the saved window data.

**Comment by karnthis** [comment]
I know this is an old issue, just just wanted to leave a note for others that might have the issue. `loadURL()` is the wrong method to be using in this situation. Before a window is `open()`ed, `setURL()` is used to define the window url if it is not done as part of `createNew()`. `loadURL()` is done after `open()`. Example code:

```
var win2 = windowManager.createNew('win2', 'Windows #2');
win2.setURL('https://www.facebook.com');
win2.open();
win2.loadURL('https://www.google.com');
```

**Comment by a-sync** [comment]
It's also hinted in the README.md, just under setURL :)
> ... to open a URL after the window is open use loadURL().
