### ISSUE TITLE
Issue adding listeners to main window.

### ISSUE THREAD

**Issue by DeanPackard** [TamkeenLMS/electron-window-manager#43]
I am having a lot of difficulty adding listeners to my main window. I had this application working properly before trying to change everything over into using window manager. The key parts of my code that aren't working are here where I assign the new window to a variable "mainWindow"
var mainWindow = windowManager.createNew('home', 'welcome', `file://${__dirname}/index.html`);

and here where I have listeners for them
 mainWindow.on('minimize',function(event){
            event.preventDefault()
            mainWindow.hide();
        });
        
    mainWindow.on('close', function (event) {
        if( !app.isQuiting){
            event.preventDefault()
            mainWindow.hide();
        }

I get an error that says mainWindow.on() is not a function. is what windowManager returns not a browser window?

**Comment by DeanPackard** [comment]
I found the solution. windowManager.createNew(....) only gives you a window object, in order to get a browser window, which allows you to show, hide, and add listeners, you do something like this
            mainWindow = windowManager.createNew('home', 'welcome', `file://${__dirname}/index.html`);
            mainWindow.create();
            mainWindow.object.show();

**Comment by telferha** [comment]
thanks for posting the solution, worked great; like me some might assume the Window class _is a_ browser window but after looking at the actual script the Window class stores its instance of Electron's BrowserWindow. 

BUT I wanted to add that when getting a reference to the window from the windowManager ( ie using windowManager.getCurrent() ) , it will return the BrowserWindow instance not the Window

**Comment by DeanPackard** [comment]
thanks!
