### ISSUE TITLE
Has this project been abandoned?

### ISSUE THREAD

**Issue by roypardi** [TamkeenLMS/electron-window-manager#50]
Has this project been abandoned?
If so it would be good to let folks know.

**Comment by TamkeenLMS** [comment]
@roypardi This is an open source project, and it's open for anyone who wants to contribute to its development. As for use, we don't have the time to do that at the moment. But any contributions are welcome.

**Comment by roypardi** [comment]
In other words you have abandoned it. That's cool – we understand – but people should be aware of that (for example there are 3 active pull requests going back months).

Better to state that you are no longer supporting it

**Comment by a-sync** [comment]
I'm happy to say it's not!
