### ISSUE TITLE
Please update the code on npm to match the github repository

### ISSUE THREAD

**Issue by a-sync** [TamkeenLMS/electron-window-manager#51]
Hi there,
the current github commit is way behind the code in npm (1.0.1 vs 1.0.4).

This is causing a lot of issues for people who are unaware of this, and try to use / improve the code.
It also makes it impossible to send in pull requests for the most recent version.

Please make the time and update this repo to reflect npm!

Thanks.

**Comment by TamkeenLMS** [comment]
@a-sync Sorry I don't really understand. The code is the same on both ends, I just checked myself. Are you talking about creating a release here on gitub ?

As for the code, it's indeed becoming old and ugly for the current state of JS, but I just cannot make any promises about a new release. It's an open source project after all, and anyone is more than welcome to improve on this library.

Thanks

**Comment by a-sync** [comment]
What exact code did you compare? I assume you mean github / npm as both ends.

The npm repo here: https://www.npmjs.com/package/electron-window-manager shows the current version as **1.0.4** published a year ago. 
After downloading it from npm, the package.json has version **1.1.0** in it. 
```bash
$> npm view electron-window-manager versions
[ '1.0.0', '1.0.1', '1.0.2', '1.0.3', '1.0.4', '1.1.0' ]
```
**1.0.1** is in the current github repo so atleast the package.json is different.

Comparing the content of the index.js file shows all the differences:
https://www.diffchecker.com/kxuicDhy
NPM version on the left & github version on the right (@ 8e8bf0 commit to exclude the new merges)
Also here is the commit on my fork which updates the github code to match the code on npm: https://github.com/a-sync/electron-window-manager/commit/1cfb67deb84005262023f71e3a480a955cbe481d

Please take another look, bump the patch version and push an updated release to npm stable channel.

Thanks!

**Comment by TamkeenLMS** [comment]
Ah, I understand. So, I have changed the version inside the package.json on github, this should solve the issue, did it?!

Thanks

**Comment by a-sync** [comment]
Well sort of... but not really. Would it not make more sense to bump the version (assuming ewm follows semver) to reflect that this repo has changes and push a new (pre)release on npm to keep everything up to date and in sync? (1.0.5)
(Most important would be the watchjs dependency fix which affects 1.0.4 which is the currently installed version by default.)

I took a thorough look at the released npm packages and noticed that there is indeed an 1.1.0 version, but the file mod dates inside the package put it a day before the 1.0.1 release so i'm guessing it was an error and was later removed. (Not sure while it is still available from npm, but package downloader addons still download it as the latest release matching ^1.0.0)

You can check this yourself by entering a temp folder, and running the following:
`npx npm-package-downloader -a -p electron-window-manager -o .`

I also found the commit that matches the 1.0.4 release (with the exception of the version number that you just changed in the package json file which was pushed to npm but not committed here apparently). 
https://github.com/TamkeenLMS/electron-window-manager/tree/df8ebdbd62bc0fedff545f0b801b24e56e72e659

When i created the issue i was under the impression that the git repo was behind the npm repo but clearly that is not the case. Checking all the commits between df8ebdb and the current HEAD it seems like there have been a lot of fixes / changes, which makes me wonder why no new npm release was pushed?

Releasing a new version with the code in it's current state is probably a bad idea (new commits not tested by the users of ewm relying only on npm; also noticed a bad merge which i reflect on in #52), and i would gladly help to fix what i can but all this would only make sense if we can push the updates to npm where everyone can benefit from it. If the pull requests only affect the github repo the majority of users wont get any updates, and there will be no feedback about changes.

Sorry for the wall of text, i hope i made my worries clear.
Kind regards,
  a-sync

**Comment by a-sync** [comment]
@TamkeenLMS thanks for the contrib offer, and sorry for the delay.
I pushed a new branch (#release-v1.0.5) which is a merge from current #master including all the fixes, and minor additions, with some of my own, into the df8ebdb commit. (v1.0.4 version tag added)
I bumped the version to 1.0.5 and prepared a release draft pointing to 4d4484b (new branch).

Now if you have no disagreement, please push the code at this commit to npm as v1.0.5.

While your there, please try `npm unpublish electron-window-manager@1.1.0` to completely remove the misleading release. (If this doesn't work a deprecation warning might be a good idea.)

After this i will take a look at #52 and try to merge in the latest release to #master.
If this is resolved, the open issues can be reviewed.

Kind regards,
  a-sync

**Comment by a-sync** [comment]
@TamkeenLMS can you please push the prepared release (v1.0.5) to npm? Or add me as a collaborator there, so i can do it. (same user name: a-sync)

**Comment by TamkeenLMS** [comment]
@a-sync I have added you as a collaborator. Thanks for your time and interest, and good luck.
