### ISSUE TITLE
Not possible to open a closed window

### ISSUE THREAD

**Issue by hevilp** [TamkeenLMS/electron-window-manager#56]
Hi,

I create a window, after closing it, I cannot open it again. Console says its already exists. Is there anyway to tell it, its closed?
`
function create_optionen() {
  // Create a new window
  winOption = windowManager.createNew('options', 'Optionen', false, false, {
          'width': 600,
          'height': 170,
          'resizable': true
    });
    //win1.registerShortcut('CTRL+N', function(){
      winOption.setURL(optionpfad);
      winOption.open();
      winOption.loadURL(optionpfad);
			winOption.on('closed', () => {
				winOption.destroy();
				winOption.close();
				winOption = null;
			});

}`

**Comment by hevilp** [comment]
AND: The Shortcut register does not work, thats why its commented...

**Comment by a-sync** [comment]
Please provide some more detail about your use case:
What is your ewm version?
What is your electron version?
What is your OS?
Where is this code running? main proc. or renderer?

For shortcut: please try it with: `Ctrl+N` or `CmdOrCtrl+N`. 
(The readme might be wrong.)
Also: updateing electron-localshortcut dependency to v3.1.0 might help.

**Comment by hevilp** [comment]
Hi,
"electron-window-manager": "^1.0.5",
    "electron": "1.7.10",

Windows 10

Code is running in own javasript file.

I changed the shortcut to https://electronjs.org/docs/tutorial/keyboard-shortcuts . So its not a problem anymore.

The problem is:
I open a window with a button.
If I close the Window with the "X", its closed and the console says its closed.
But I cannot reopen it, cos the instance is not really closed.

`Window "home" was created
Window "options" was created
Window "options" was closed
Window options already exists!
`

`\node_modules\electron\dist\resources\electron.asar\renderer\api\remo…:234 Uncaught Error: Could not call remote function 'createNew'. Check that the function signature is correct. Underlying error: Cannot read property 'focus' of null
Error: Could not call remote function 'createNew'. Check that the function signature is correct. Underlying error: Cannot read property 'focus' of null`

**Comment by a-sync** [comment]
This seems like a bug introduced when the removal of the reference for windows `closed` was commented out. (and later turned into an option)
I will push a new version (v1.0.6) soon with this fixed / reverted.

**Comment by hevilp** [comment]
You pushed it already?

**Comment by hevilp** [comment]
index.js from yesterday, same error again:

`function create_win1() {
  // Create a new window
  windows1 = windowManager.createNew('win1', 'Windows 1', false, false, {
          'width': 1920,
          'height': 1080,
          'resizable': true,
          'menu': null,
          //'showDevTools': true,
          //'destroyOnClose': true
    }, false);
          windows1.setURL(win1pfad);
          windows1.open();
          windows1.loadURL(win1pfad);
          windows1.object.on('closed', () => {
          win1bool = false;
          });
          win1bool = true;
    };`

Window "win1" was created
Window "win1" was closed
Window win1 already exists!

**Comment by a-sync** [comment]
Can you please confirm what version is loaded in the script you are running?
1.0.6 should have fixed the previous issue.
Also you might want to try using the github version , atleast to make sure that your package manager replaces the current one.

**Comment by hevilp** [comment]
i manually loaded the github version into my node_modules folder, and there error comes

**Comment by a-sync** [comment]
Can you please provide a minimal working example?

**Comment by hevilp** [comment]
https://pastebin.com/KFFXirbc

https://pastebin.com/HvYzuk6y

https://pastebin.com/Qjn4XXzF

Later I can upload the full sourcecode...

But there you can see how it works

**Comment by hevilp** [comment]
Oh sorry,

I saw, that I used the old version in my sourcecode in my home. You can close this.
Sorry

**Comment by a-sync** [comment]
:+1:
