### ISSUE TITLE
destroyOnClose has no effect

### ISSUE THREAD

**Issue by hevilp** [TamkeenLMS/electron-window-manager#57]
Has no effect:
`  winOption = windowManager.createNew('options', 'Optionen', false, false, {
          'width': 600,
          'height': 170,
          'resizable': true,
          'showDevTools': true,
          'destroyOnClose': true

    });`

**Comment by a-sync** [comment]
Please provide some more detail:
Are you using the npm (v1.0.5) version, or the one here on github?
What electron version are you using? 
What OS are you using?

What was the desired action? What happened instead?
Thanks.

**Comment by hevilp** [comment]
Hi,
"electron-window-manager": "^1.0.5",
"electron": "1.7.10",

Windows 10

Code is running in own javasript file.


Desired action? Instance is destroyed so its possible to reopen the window.
See https://github.com/TamkeenLMS/electron-window-manager/issues/56

**Comment by a-sync** [comment]
ewm 1.0.5 does not have this option, please see: #56
