### ISSUE TITLE
Add example to docs

### ISSUE THREAD

**Issue by Jbithell** [TamkeenLMS/electron-window-manager#58]
Please could use of `windowManager.get('home').object.` be added to docs to help first time users understand how to access all electron functions

**Comment by a-sync** [comment]
Maybe it should go under here:
https://github.com/TamkeenLMS/electron-window-manager#windowobject
A lint on the `BrowserWindow` to the electron docu?

**Comment by Jbithell** [comment]
@a-sync I've cobbled together a PR - please do edit to fit house style etc. as needed!

**Comment by a-sync** [comment]
Great! Thanks!
