### ISSUE TITLE
Layout path not work

### ISSUE THREAD

**Issue by tearsofphoenix** [TamkeenLMS/electron-window-manager#68]
Currently, `utils.getAppLocalPath()` will return a path point to `\node_modules\electron\dist\resources\default_app.asar`, which is a asar file, 
but not a folder. This caused all layout settings failed.

**Comment by a-sync** [comment]
This function is using the `app.getAppPath` api internally: https://electronjs.org/docs/api/app#appgetapppath  
Are you running your app from source, or are you using some packaging tool?  
What version of electron are you using?

**Comment by tearsofphoenix** [comment]
I found why: It's my fault to use native nodejs code in renderer process. My project is using ported `fs` apis.
After moved those code into main process, all problem solved.
